In [3]:
import numpy as np
import pandas as pd
import csv as csv

climate = pd.read_csv('emdat_data.csv', header=0)
print(climate)

      year            region         disaster type  occurrence  Total deaths  \
0     1900         Caribbean              Epidemic           1            30
1     1900         Caribbean                 Flood           1           300
2     1900  Northern America                 Storm           1          6000
3     1902         Caribbean     Volcanic activity           2         31565
4     1902   Central America            Earthquake           2          2185
5     1902   Central America     Volcanic activity           2          7000
6     1903         Caribbean                 Storm           1            65
7     1903  Northern America                 Flood           2           250
8     1903  Northern America   Mass movement (dry)           1            76
9     1903  Northern America                 Storm           1            98
10    1904     South America            Earthquake           1             0
11    1905  Northern America   Mass movement (dry)           1            18
12    1906   Central America            Earthquake           2          1000
13    1906  Northern America            Earthquake           1          2000
14    1906  Northern America                 Storm           2           298
15    1906     South America            Earthquake           3         20400
16    1907         Caribbean            Earthquake           1          1200
17    1908  Northern America   Mass movement (dry)           1            33
18    1909         Caribbean             Landslide           1            53
19    1909         Caribbean                 Storm           1           150
20    1909  Northern America                 Flood           1            72
21    1909  Northern America                 Storm           2           391
22    1910   Central America            Earthquake           1          1750
23    1910  Northern America   Mass movement (dry)           1            62
24    1910  Northern America                 Storm           1            30
25    1911  Northern America              Wildfire           1            73
26    1912         Caribbean                 Storm           1           142
27    1912  Northern America                 Storm           1            28
28    1913  Northern America                 Storm           1           732
29    1913     South America            Earthquake           1           150
...    ...               ...                   ...         ...           ...
1036  2014   Central America              Epidemic           1             4
1037  2014   Central America  Extreme temperature            1             0
1038  2014   Central America                 Flood           5            13
1039  2014   Central America                 Storm           7            21
1040  2014  Northern America               Drought           1             0
1041  2014  Northern America            Earthquake           1             1
1042  2014  Northern America  Extreme temperature            2            21
1043  2014  Northern America                 Flood           3             2
1044  2014  Northern America             Landslide           1            43
1045  2014  Northern America                 Storm          15           136
1046  2014  Northern America              Wildfire           1             2
1047  2014     South America               Drought           2             0
1048  2014     South America            Earthquake           3            17
1049  2014     South America  Extreme temperature            1           505
1050  2014     South America                 Flood          17           200
1051  2014     South America             Landslide           2            98
1052  2014     South America                 Storm           2            11
1053  2014     South America              Wildfire           1            12
1054  2015         Caribbean                 Flood           3            11
1055  2015   Central America               Drought           1             0
1056  2015   Central America                 Flood           1             0
1057  2015   Central America                 Storm           3            34
1058  2015   Central America     Volcanic activity           1             0
1059  2015  Northern America                 Flood           2            48
1060  2015  Northern America                 Storm           9            95
1061  2015     South America            Earthquake           1             0
1062  2015     South America                 Flood           7           217
1063  2015     South America             Landslide           2            98
1064  2015     South America                 Storm           2            10
1065  2015     South America     Volcanic activity           3             0

      Affected  Injured  Homeless  Total affected  Total damage
0            0        0         0               0             0
1            0        0         0               0             0
2            0        0         0               0         30000
3            0        0         0               0             0
4            0        0         0               0             0
5            0        0         0               0             0
6            0        0         0               0             0
7            0        0         0               0        480000
8            0       23         0              23             0
9            0        0         0               0             0
10           0        0         0               0             0
11           0       18         0              18             0
12           0        0         0               0             0
13           0        0         0               0        524000
14           0        0         0               0             0
15           0        0         0               0        100000
16       90000        0         0           90000         30000
17           0        0         0               0             0
18           0        0         0               0             0
19           0        0         0               0             0
20           0        0         0               0             0
21           0        0         0               0             0
22           0        0         0               0             0
23           0        0         0               0             0
24           0        0         0               0             0
25           0        0       200             200             0
26           0        0     94820           94820             0
27           0      200      2500            2700          5000
28           0        0         0               0        200000
29           0        0         0               0             0
...        ...      ...       ...             ...           ...
1036     12783        0         0           12783             0
1037      8141        0         0            8141             0
1038     83461        0         0           83461          1400
1039    244000      135         0          244135       2539500
1040         0        0         0               0       2200000
1041      3000      250         0            3250        700000
1042         0        0         0               0       2500000
1043    108900        4         0          108904       1819000
1044         0        0       150             150         20000
1045      1734       51        30            1815      10170000
1046       429        0         0             429        100000
1047  27051180        0         0        27051180       5000000
1048    513987       22         0          514009        100000
1049    109257        0         0          109257             0
1050   1138675       52     70200         1208927        270000
1051      6950        0      4800           11750        200000
1052         0       25      2000            2025             0
1053     10500      500         0           11000         34000
1054     75939        0       100           76039             0
1055     85000        0         0           85000         60000
1056      9666        0         0            9666             0
1057     22592      286       750           23628             0
1058     18450        0         0           18450             0
1059     24000        0         0           24000       1000000
1060         0       69         0              69       3525000
1061       600        1         0             601             0
1062    435370        0     31379          466749             0
1063         0       37       300             337             0
1064     14500       25         0           14525             0
1065      7600        0         0            7600             0

[1066 rows x 10 columns]

In [4]:
climate.head()

,year,region,disaster type,occurrence,Total deaths,Affected,Injured,Homeless,Total affected,Total damage
0,1900,Caribbean,Epidemic,1,30,0,0,0,0,0
1,1900,Caribbean,Flood,1,300,0,0,0,0,0
2,1900,Northern America,Storm,1,6000,0,0,0,0,30000
3,1902,Caribbean,Volcanic activity,2,31565,0,0,0,0,0
4,1902,Central America,Earthquake,2,2185,0,0,0,0,0

In [19]:
%matplotlib inline
from matplotlib.colors import ListedColormap
cmap_bold = ListedColormap(['#FF0000', '#00FF00', '#0000FF'])

climate['disaster_type'] = climate({'Earthquake':0, 'Flood':1, 'Storm':2})
climate.plot(kind='scatter', x='Total_deaths', y='Affected', c='Injured', colormap=cmap_bold)

TypeError: 'DataFrame' object is not callable